### ISSUE TITLE
This plug-in does not work well on my computer

### ISSUE THREAD

**Issue by zhaihr23** [divinites/LatexEquationPreview#4]
I use Sublime Text 3 and MikTex to build my latex environment. Everything works well but this equation preview plug-in does not work well on my computer. When I click "check system", it tells me that the program magick is missing. What should I do to make it well?
What's more, I have installed imagemagick and have added it to path. But it still remains the same.

![default](https://user-images.githubusercontent.com/26818388/33512302-88cbd052-d768-11e7-8f0a-ba0a2a7d6387.PNG)

**Comment by divinites** [comment]
Have you chosen legacy support when installing imagemagick?

**Comment by divinites** [comment]
I suppose that your problem is solved.
